[workspace]
resolver = "2"
members = [
    ".", # Current package (zen404 library and binary)
    "xtask",
]

[package]
name = "zen404"
version = "0.1.0"
<<<<<<< HEAD
edition = "2021"
=======
edition = "2021" # Keep consistent with xtask or choose latest
>>>>>>> ecc0b6f (feat: Migrate build and dev tasks from mise to cargo xtask)

[lib]
name = "zen404"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
jsonschema = "0.17.1"
<<<<<<< HEAD
json_comments = "0.2" # Added for JSON3/JSONC parsing support

[dev-dependencies]
rand = "0.8"
=======

[dev-dependencies]
rand = "0.8"
# xtask is no longer a dev-dependency of the root package
>>>>>>> ecc0b6f (feat: Migrate build and dev tasks from mise to cargo xtask)

[profile.release]
lto = true
panic = "abort"

[profile.dev]
panic = "abort"

[[bin]]
name = "zen404"
path = "src/main.rs"

[[bin]]
name = "fuckup"
path = "fuckup/main.rs"
<<<<<<< HEAD
=======

# The xtask binary definition is removed from here,
# as it's now its own package in the workspace.
# [[bin]]
# name = "xtask"
# path = "xtask/main.rs"
>>>>>>> ecc0b6f (feat: Migrate build and dev tasks from mise to cargo xtask)
