accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MPL-2.0",
    "Zlib",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "BSL-1.0",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "OpenSSL",
    "WTFPL",
    "LicenseRef-Slint-Software-3.0",
]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin"]
ignore-dev-dependencies = true
filter-noassertion = true

# See https://embarkstudios.github.io/cargo-about/cli/generate/workarounds.html
workarounds = ["ring"]
