[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
description = "Xtask commands for automation tasks"
license = "MIT OR Apache-2.0"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
