[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
description = "Xtask commands for automation tasks"
license = "ISC"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
anyhow = "1.0"
